# generator_ckpt: checkpoints/ode_init.pt
generator_fsdp_wrap_strategy: size
real_score_fsdp_wrap_strategy: size
fake_score_fsdp_wrap_strategy: size
real_name: Qwen-Image
fake_name: Qwen-Image
generator_type: bidirectional
generator_name: Qwen-Image
text_encoder_fsdp_wrap_strategy: size
text_encoder_cpu_offload: false
denoising_step_list:
  - 1000
  - 750
  - 500
  - 250
warp_denoising_step: true # need to remove - 0 in denoising_step_list if warp_denoising_step is true
ts_schedule: false
num_train_timestep: 1000
timestep_shift: 3.0
guidance_scale: 4.0
denoising_loss_type: flow
mixed_precision: true
seed: 0
wandb_host: WANDB_HOST
wandb_key: WANDB_KEY
wandb_entity: WANDB_ENTITY
wandb_project: WANDB_PROJECT
sharding_strategy: full
lr: 2.0e-06
lr_critic: 4.0e-07
beta1: 0.0
beta2: 0.999
beta1_critic: 0.0
beta2_critic: 0.999
data_type: text_file
data_path: prompts.txt
data_max_count: 30000
batch_size: 1
ema_weight: 0.99
ema_start_step: 200
total_batch_size: 64
log_iters: 200
negative_prompt: ' '
dfake_gen_update_ratio: 5
distribution_loss: dmd
trainer: score_distillation
gradient_checkpointing: true
model_kwargs:
  timestep_shift: 3.0
  pretrain_weight: 30-step-13000.safetensors